secrets:
  - name: clickhouse-credentials
    src-namespace: clickhouse
    dst-namespaces:
      - fhir-server
  - name: elastic-secret
    src-namespace: elastic
    dst-namespaces:
      - fhir-server
  - name: mongodb
    src-namespace: mongodb
    dst-namespaces:
      - fhir-server
  - name: redis
    src-namespace: redis
    dst-namespaces:
      - fhir-server
  - name: user
    src-namespace: kafka
    dst-namespaces:
      - fhir-server
      - clickhouse