secrets:
  - name: clickhouse-credentials # src secret name
    src-namespace: clickhouse    # src namespace
    dst-namespaces:              # dst namespaces
      - fhir-server
  - name: minio
    src-namespace: minio
    overwrite:                                # overwrite options
      dagster:                                # dst namespace
        dst-secret-name: dagster-minio-secret # dst secret name after overwrite
        dst-keys:                             # data keys name <before: after>
          rootPassword: AWS_SECRET_ACCESS_KEY
          rootUser: AWS_ACCESS_KEY_ID
    dst-namespaces:
      - dagster
