---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - internal.edenlab.io
  resources:
  - secretssyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - internal.edenlab.io
  resources:
  - secretssyncs/finalizers
  verbs:
  - update
- apiGroups:
  - internal.edenlab.io
  resources:
  - secretssyncs/status
  verbs:
  - get
  - patch
  - update
