# permissions for end users to view secretssyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretssync-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secrets-sync
    app.kubernetes.io/part-of: secrets-sync
    app.kubernetes.io/managed-by: kustomize
  name: secretssync-viewer-role
rules:
- apiGroups:
  - internal.edenlab.io
  resources:
  - secretssyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - internal.edenlab.io
  resources:
  - secretssyncs/status
  verbs:
  - get
