apiVersion: internal.edenlab.io/v1alpha1
kind: SecretsSync
metadata:
  labels:
    app.kubernetes.io/name: secretssync
    app.kubernetes.io/instance: secretssync-sample
    app.kubernetes.io/part-of: secrets-sync
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secrets-sync
  name: secretssync-sample
spec:
  secrets:
    mongodb:                                                 # required
      srcNamespace: mongodb                                  # required
      dstSecrets:                                            # option
        - name: mongodb-1                                    # option
          keys:                                              # option
            mongodb-replica-set-key: MONGODB_REPLICA_SET_KEY # option
            mongodb-root-password: MONGODB_ROOT_PASSWORD     # option
        - name: mongodb-2                                    # option
    elastic-secret:                                          # required
      srcNamespace: elastic                                  # required
    redis:                                                   # required
      srcNamespace: redis                                    # required
